import{SOURCE,MODULE_URL,PRESETS,parseNumber,parseProfile,calculate}from'./model.mjs';
const $=id=>document.getElementById(id);const fmt=n=>n!==0 && Math.abs(n)<.000001?n.toExponential(4):n.toLocaleString('en-GB',{maximumFractionDigits:3});let engine,current;const NS='http://www.w3.org/2000/svg';
$('code').href=`https://github.com/${SOURCE.repository}/blob/${SOURCE.commit}/${SOURCE.file}`;$('proof').href=`https://github.com/${SOURCE.repository}/blob/${SOURCE.commit}/proofs/connection-capacity.proof.mjs`;$('provenance').textContent=`${SOURCE.repository} / ${SOURCE.commit} / ${SOURCE.file}\nSHA256 ${SOURCE.sha256}`;
function shape(tag,attrs,parent,text){const node=document.createElementNS(NS,tag);for(const[key,value]of Object.entries(attrs))node.setAttribute(key,String(value));if(text!==undefined)node.textContent=text;parent.append(node);return node;}
function inspect(){if(!current)return;const i=Number($('interval').value)-1,ex=current.intervals[i],{intervalHours}=current.inputs;const x=80+i*530/current.intervals.length;$('cursor').replaceChildren();shape('rect',{class:'selection',x,y:50,width:530/current.intervals.length,height:260},$('cursor'));$('intervalDetail').textContent=`Interval ${i+1} · ${fmt(i*intervalHours)}–${fmt((i+1)*intervalHours)} h: ${fmt(ex.peakKw)} kW, ${fmt(ex.peakExcessKw)} kW excess and ${fmt(ex.energyAboveCapKwh)} kWh above cap.`;}
function draw(){const{inputs,summary}=current;const max=Math.max(summary.peakKw,inputs.capKw)*1.2;const y=value=>310-value/max*240;for(const id of['grid','bars','capLine'])$(id).replaceChildren();shape('path',{class:'axis',d:'M80 50 V310 H610'},$('grid'));shape('text',{x:80,y:28},$('grid'),'kW');shape('text',{x:75,y:337,'text-anchor':'end'},$('grid'),'0');shape('text',{x:610,y:352,'text-anchor':'end'},$('grid'),`${fmt(summary.spanHours)} h`);shape('text',{x:80,y:352},$('grid'),'0 h');shape('text',{x:610,y:28,'text-anchor':'end'},$('grid'),`Peak ${fmt(summary.peakKw)} kW`);
  inputs.profileKw.forEach((value,i)=>{const x=80+i*530/inputs.profileKw.length,w=530/inputs.profileKw.length;const group=shape('g',{class:'bar',style:`animation-delay:${i*12}ms`},$('bars'));shape('rect',{class:'below',x,y:y(Math.min(value,inputs.capKw)),width:w,height:310-y(Math.min(value,inputs.capKw))},group);if(value>inputs.capKw)shape('rect',{class:'above',x,y:y(value),width:w,height:y(inputs.capKw)-y(value)},group);shape('title',{},group,`Interval ${i+1}: ${fmt(value)} kW`);});
  shape('line',{class:'cap',x1:80,x2:610,y1:y(inputs.capKw),y2:y(inputs.capKw)},$('capLine'));shape('text',{x:84,y:y(inputs.capKw)-9},$('capLine'),`Cap ${fmt(inputs.capKw)}`);$('chartDescription').textContent=`${inputs.profileKw.length} equal intervals of ${fmt(inputs.intervalHours)} hours. Peak excess ${fmt(summary.peakExcessKw)} kW; energy above cap ${fmt(summary.energyAboveCapKwh)} kWh. Amber rectangles mark power above the stated cap.`;$('interval').max=String(inputs.profileKw.length);$('interval').value=String(Math.min(Number($('interval').value),inputs.profileKw.length));inspect();}
function refresh(){current=null;$('download').disabled=true;if(!engine)return;try{current=calculate(engine,{profileKw:parseProfile($('profile').value),capKw:parseNumber($('cap').value),intervalHours:parseNumber($('hours').value)});const r=current.summary;$('peak').textContent=`${fmt(r.peakExcessKw)} kW`;$('energy').textContent=`${fmt(r.energyAboveCapKwh)} kWh`;$('quick').textContent=`${fmt(r.peakExcessKw)} kW peak excess · ${fmt(r.energyAboveCapKwh)} kWh above the stated cap`;$('totals').textContent=`${r.intervalsAboveCap} of ${r.intervalCount} intervals above cap (${fmt(r.fractionOfTimeAboveCap*100)}% of this period). Total profile energy: ${fmt(r.siteEnergyKwh)} kWh across ${fmt(r.spanHours)} h.`;$('loadFactor').textContent=typeof r.siteLoadFactor==='number'?`Load factor: ${fmt(r.siteLoadFactor*100)}% = average active power / peak interval-average power.`:'Load factor undefined: the zero profile would divide zero by zero.';$('record').textContent=JSON.stringify(current,null,2);$('error').hidden=true;$('result').hidden=false;$('status').textContent=`Computed by the pinned module · ${current.moduleCalls} direct calls`;$('download').disabled=false;draw();}catch(error){current=null;$('result').hidden=true;$('error').hidden=false;$('error').textContent=`REFUSED · ${error.name}: ${error.message}`;$('quick').textContent='Input refused; previous result cleared.';$('record').textContent='No current result.';$('status').textContent='No current calculation.';}}
$('controls').addEventListener('submit',event=>{event.preventDefault();refresh();});$('controls').addEventListener('input',refresh);$('interval').addEventListener('input',inspect);document.querySelectorAll('[data-preset]').forEach(button=>button.addEventListener('click',()=>{$('profile').value=PRESETS[button.dataset.preset].join(', ');$('cap').value='30000';$('hours').value='.5';refresh();}));
for(const[id,reason]of Object.entries({wafer:'No numbered line established for this element: no issued code-line mapping has been verified for the synthetic profile.',application:'No registered application URL established for this calculation.',tools:'No manifest layer established for this calculation; no tool target is invented.'}))$(id).addEventListener('click',()=>{$('handoff').textContent=reason;});
$('download').addEventListener('click',()=>{if(!current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(current,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='power-profile.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
try{engine=await import(MODULE_URL);refresh();}catch(error){$('quick').textContent='Calculation module unavailable.';$('status').textContent='No substitute arithmetic.';$('error').hidden=false;$('error').textContent=error.message;}
if(document.modelContext?.registerTool){const lifecycle=new AbortController();addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'read_power_profile',description:'Read the current synthetic power profile and cap comparison without changing it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input || typeof input!=='object' || Array.isArray(input) || Object.keys(input).length)throw new TypeError('Expected empty object');return current?JSON.parse(JSON.stringify(current)):{available:false,status:$('status').textContent};}});
  register({name:'configure_power_profile',description:'Set equal-duration synthetic kW values and a stated kW cap; run the visible profile arithmetic. Does not size a battery or approve a connection.',inputSchema:{type:'object',properties:{profileKw:{type:'array',minItems:1,maxItems:48,items:{type:'number',minimum:0,maximum:1e7}},capKw:{type:'number',minimum:.001,maximum:1e7},intervalHours:{type:'number',minimum:1/3600,maximum:24}},required:['profileKw','capKw','intervalHours'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!engine)throw new Error('Module unavailable');if(!input || typeof input!=='object' || Array.isArray(input) || Object.keys(input).some(key=>!['profileKw','capKw','intervalHours'].includes(key)))throw new TypeError('Unexpected fields');calculate(engine,input);$('profile').value=input.profileKw.join(', ');$('cap').value=String(input.capKw);$('hours').value=String(input.intervalHours);refresh();return JSON.parse(JSON.stringify(current));}});
}
