import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';const digest=value=>createHash('sha256').update(value).digest('hex');
const root=process.argv[2];if(!root)throw Error('Generation directory required');
const manifest=JSON.parse(await fs.readFile(path.join(root,'manifest.json'),'utf8'));const tables={},relations=new Map();let bytes=0,files=0,max=0;
async function read(entry){const resolved=path.resolve(root,entry.path);if(!resolved.startsWith(path.resolve(root)+path.sep))throw Error('Escaping manifest path');const b=await fs.readFile(resolved);if(b.length>=600000||b.length!==entry.bytes||digest(b)!==entry.sha256)throw Error('Hash/size mismatch: '+entry.path);bytes+=b.length;max=Math.max(max,b.length);files++;return JSON.parse(b);}
for(const e of manifest.relations||[])relations.set(e.path,await read(e));
function expand(value){if(Array.isArray(value))return value;if(value?.parts){const result=value.parts.flatMap(p=>{if(!relations.has(p))throw Error('Missing relation part');return relations.get(p);});if(result.length!==value.count)throw Error('Relation count mismatch');return result;}throw Error('Missing relation array');}
for(const[kind,entries]of Object.entries(manifest.indexes)){const map=new Map();tables[kind]=map;for(const e of entries){const rows=await read(e);if(rows.length!==e.count||rows[0]?.n!==e.first||rows.at(-1)?.n!==e.last)throw Error('Index bounds mismatch');for(const r of rows){if(map.has(r.n))throw Error('Duplicate primary key');for(const[k,v]of Object.entries(r))if(v?.parts)r[k]=expand(v);map.set(r.n,r);}}}
const countNames={line:'lines',family:'families',tablet:'tablets',source:'sources',block:'blocks',repository:'repositories'};
for(const[kind,name]of Object.entries(countNames))if(tables[kind].size!==manifest.counts[name])throw Error('Primary key count mismatch: '+kind);
const has=(kind,n)=>{if(!tables[kind]?.has(n))throw Error(`Unresolved ${kind} key ${n}`);return tables[kind].get(n);};
for(const r of tables.line.values()){if(digest(Buffer.from(r.base64,'base64'))!==r.sha256)throw Error('Stored line byte hash mismatch');for(const n of r.families)if(!has('family',n).lines.includes(r.n))throw Error('Missing reverse family-to-line relation');for(const n of r.tablets)if(!has('tablet',n).lines.includes(r.n))throw Error('Missing reverse tablet-to-line relation');}
for(const r of tables.family.values()){for(const n of r.lines)if(!has('line',n).families.includes(r.n))throw Error('Missing reverse line-to-family relation');for(const n of r.tablets)has('tablet',n);for(const n of r.uses)if(!has('family',n).used_by.includes(r.n))throw Error('Missing reverse dependency candidate');for(const n of r.used_by)if(!has('family',n).uses.includes(r.n))throw Error('Missing forward dependency candidate');for(const n of r.blocks)if(!has('block',n).families.includes(r.n))throw Error('Missing reverse group membership');}
for(const r of tables.tablet.values()){for(const n of r.lines)if(!has('line',n).tablets.includes(r.n))throw Error('Missing reverse line-to-tablet relation');for(const n of r.sources)if(has('source',n).tablet!==r.n)throw Error('Source/tablet mismatch');for(const n of r.families)if(!has('family',n).tablets.includes(r.n))throw Error('Tablet/family mismatch');}
for(const r of tables.source.values()){if(!/^[a-f0-9]{40}$/.test(r.commit)||digest(JSON.stringify([r.repo,r.commit,r.path]))!==r.n)throw Error('Invalid pinned source identity');if(!has('tablet',r.tablet).sources.includes(r.n))throw Error('Missing reverse source occurrence');}
for(const r of tables.block.values())for(const n of r.families)if(!has('family',n).blocks.includes(r.n))throw Error('Missing forward membership');
for(const r of tables.repository.values()){for(const n of r.families)has('family',n);for(const n of r.sources)if(has('source',n).repo!==r.n)throw Error('Repository/source mismatch');}
bytes+=(await fs.stat(path.join(root,'manifest.json'))).size;if(bytes>=200000000)throw Error('200 MB publication bound exceeded');
console.log(JSON.stringify({observed_utc:new Date().toISOString(),passed:true,source_commit:manifest.source_commit,database_sha256:manifest.database_sha256,counts:manifest.counts,total_bytes:bytes,files:files+1,max_file_bytes:max,checks:['shard hashes and sizes','all permanent key counts','all exact line byte hashes','reciprocal line/family/tablet membership','reciprocal candidate dependencies','reciprocal block membership','full-commit source identity','repository source ownership'],scope:manifest.scope},null,2));
