'use strict';
const el=id=>document.getElementById(id),cache=new Map();let manifest,current,entries=[],offset=0,serial=0;
const labels={family:'Family',line:'Line',block:'Block',tablet:'Source tablet',source:'Pinned source',repository:'Repository'};
const relKinds={families:'family',lines:'line',tablets:'tablet',sources:'source',uses:'family',used_by:'family',blocks:'block'};
const relLabels={families:'Recorded families',lines:'Permanent line keys',tablets:'Source tablets',sources:'Pinned source occurrences',uses:'Candidate uses',used_by:'Candidate used by',blocks:'Block memberships'};
async function json(file){if(cache.has(file))return cache.get(file);const r=await fetch('data/'+file);if(!r.ok)throw Error('Missing snapshot input: '+file+' (HTTP '+r.status+')');const value=await r.json();cache.set(file,value);if(cache.size>10)cache.delete(cache.keys().next().value);return value;}
async function record(kind,key){const list=manifest.indexes[kind];if(!list)throw Error('Unknown record type');key=['line','family','tablet'].includes(kind)?Number(key):String(key);const part=list.find(p=>key>=p.first&&key<=p.last);if(!part)throw Error('Permanent key not present in this snapshot');const r=(await json(part.path)).find(r=>r.n===key);if(!r)throw Error('Indexed key missing');return r;}
async function array(value){if(Array.isArray(value))return value;if(value?.parts){const result=[];for(const p of value.parts)result.push(...await json(p));if(result.length!==value.count)throw Error('Relation count mismatch');return result;}throw Error('Missing relation input');}
function go(kind,key){location.hash=new URLSearchParams({kind,key}).toString();}
function button(text,action){const b=document.createElement('button');b.textContent=text;b.addEventListener('click',action);return b;}
function svg(tag,attrs,text){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text)n.textContent=text;return n;}
function render(){const subset=entries.slice(offset,offset+12);el('items').replaceChildren();el('graph').replaceChildren();const graph=el('graph');const center=svg('g',{});center.append(svg('rect',{x:370,y:185,width:260,height:60,rx:6}),svg('text',{x:385,y:220},(el('title').textContent||'Records').slice(0,30)));graph.append(center);
 subset.forEach((item,i)=>{const x=i<6?10:750,y=10+(i%6)*70;graph.prepend(svg('line',{x1:500,y1:215,x2:x+115,y2:y+25}));const group=svg('g',{tabindex:0,role:'button','aria-label':item.label});group.append(svg('rect',{x,y,width:240,height:50,rx:5}),svg('text',{x:x+8,y:y+29},item.label.slice(0,31)));const open=()=>go(item.kind,item.key);group.addEventListener('click',open);group.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}});graph.append(group);el('items').append(button(item.label,open));});
 el('position').textContent=`${entries.length?offset+1:0}–${Math.min(offset+12,entries.length)} of ${entries.length} relationships`;el('previous').disabled=offset===0;el('next').disabled=offset+12>=entries.length;
}
async function chooseRelation(){const field=el('relation').value;entries=field?(await array(current.record[field])).map(key=>({kind:relKinds[field],key,label:`${labels[relKinds[field]]} ${key}`})):[];offset=0;render();}
async function show(){const own=++serial;try{const p=new URLSearchParams(location.hash.slice(1)),kind=p.get('kind')||'block',key=p.get('key');el('kind').value=kind;el('detail').replaceChildren();el('code').hidden=true;el('relation').replaceChildren();
 if(key===null){el('title').textContent='Browse '+labels[kind].toLowerCase()+' records';entries=[];for(const part of manifest.indexes[kind]){for(const row of await json(part.path))entries.push({kind,key:row.n,label:`${labels[kind]} ${row.n}${row.names?.length?' '+row.names[0]:''}`});}if(own!==serial)return;current=null;offset=0;render();return;}
 const r=await record(kind,key);if(own!==serial)return;current={kind,record:r};el('key').value=key;el('title').textContent=`${labels[kind]} ${r.n}${r.names?.length?' · '+r.names.join(' / '):''}`;
 if(r.scope){const p=document.createElement('p');p.textContent=r.scope;el('detail').append(p);}
 if(kind==='line'){const bytes=Uint8Array.from(atob(r.base64),c=>c.charCodeAt(0));const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==r.sha256)throw Error('Line checksum mismatch');el('code').textContent=new TextDecoder().decode(bytes);el('code').hidden=false;el('detail').textContent=`Exact stored bytes verified: SHA-256 ${hash}`;}
 if(kind==='source'){const a=document.createElement('a');a.href='https://github.com/'+r.repo+'/blob/'+r.commit+'/'+r.path.split('/').map(encodeURIComponent).join('/');a.textContent='Open file at recorded commit '+r.commit;a.target='_blank';a.rel='noopener';el('detail').append(a);r.tablets=[r.tablet];}
 for(const field of Object.keys(relKinds))if(r[field]){const count=Array.isArray(r[field])?r[field].length:r[field].count;const o=document.createElement('option');o.value=field;o.textContent=`${relLabels[field]} (${count})`;el('relation').append(o);}await chooseRelation();
 }catch(e){el('title').textContent='Record unavailable';el('detail').textContent=e.message;entries=[];render();}}
el('back').onclick=()=>history.back();el('home').onclick=()=>{location.hash='kind=block';};el('open').onclick=()=>go(el('kind').value,el('key').value);el('browse').onclick=()=>{location.hash='kind='+el('kind').value;};el('relation').onchange=()=>chooseRelation().catch(e=>{el('detail').textContent=e.message;});el('previous').onclick=()=>{offset=Math.max(0,offset-12);render();};el('next').onclick=()=>{offset+=12;render();};addEventListener('hashchange',show);
(async()=>{manifest=await json('manifest.json');el('status').textContent=`${manifest.counts.lines} permanent line keys · ${manifest.counts.families} retained family keys · ${manifest.counts.repositories} repositories\nSnapshot ${manifest.observed_utc} · source ${manifest.source_commit}\nHistorical keys are retained; no supersession mapping is inferred.`;await show();})().catch(e=>{el('status').textContent='Snapshot unavailable: '+e.message;});
