from pathlib import Path
import json,hashlib,subprocess,shutil
R=Path(__file__).resolve().parents[1];G='202609051300';D=R/G
W=Path('C:/Users/vikra/globalgrid-testcode-publication')
def read(p):return p.read_text(encoding='utf-8-sig')
def write(p,s):p.write_text(s,encoding='utf8',newline='\n')
checks=json.loads(read(D/'evidence/five-journeys.json'))['checks'];assert len(checks)==10 and all(c['ok'] for c in checks)
p=D/'index.html';s=read(p);start=s.index('<p>Arrival correction:');end=s.index('<div class="pair">',start)
s=s[:start]+'<p>Five Pipeline-to-MAP journeys retested in Chrome. Search and calculation cards stay separate; the map frames the project and measured endpoints. Morgan now calculates from a labelled approximate Crown Estate lease-area centre. <a href="../202609051214/">Previous Test Code build 202609051214</a>.</p>'+s[end:];write(p,s)
p=D/'pipeline/index.html';s=read(p).replace('Missing geometry remains in search and CSV and opens DETAILS with the missing-location reason.','Records without REPD geometry remain in search and CSV. Morgan MAP uses an attributed approximate Crown Estate lease-area centre; other unresolved locations open DETAILS.');write(p,s)
p=D/'release.json';j=json.loads(read(p));j['changes'].append('Morgan REPD 10919 uses a pinned Crown Estate lease-area centroid for explicitly approximate grid screening.');j['changes']=[v for v in j['changes'] if 'Retain pinned' not in v];j['limitations']=['Other coordinate-less records, including REPD 11613, remain unresolved.','General search Parquet failure is not fixed by this exact-arrival path.','Mobile checks are Chrome Pixel 7 emulation, not an Android device or iPhone.'];j['location_provenance']='atlas/data/project-areas/10919-provenance.json';write(p,json.dumps(j,indent=2)+'\n')
rows=''.join(f'<tr><td>{c["profile"]}</td><td>{c["ref"]}</td><td>Calculation and layout checked</td><td><a href="evidence/{c["profile"]}-{c["ref"]}.png">Screenshot</a></td></tr>' for c in checks)
real=json.loads(read(D/'evidence/real-chrome-five.json'))
links=''.join(f'<li>REPD {c["ref"]}: <a href="evidence/{c["screenshot"]}">Real Chrome screenshot</a></li>' for c in real)
write(D/'results.html','<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Test Code '+G+' evidence</title><style>body{max-width:1000px;margin:24px auto;padding:16px;background:#08151c;color:#e3f5fa;font:16px/1.5 system-ui}a{color:#9eeaff}td,th{padding:8px;border-bottom:1px solid #456}table{width:100%}</style><a href="./">Test Code</a><h1>Five actual Pipeline-to-MAP journeys</h1><p>Real Chrome extension: Norfolk Vanguard East, Caledonia South, Thorpe Marsh, West of Orkney and Morgan all displayed calculated distances. Each journey has screenshot evidence. A project name or error screen alone is a failure.</p><ul>'+links+'</ul><p>Morgan initially failed because its REPD record has no coordinates. It now uses an explicitly approximate centre of the Crown Estate lease polygon, with attribution on the card. <a href="atlas/data/project-areas/10919-provenance.json">Location provenance</a>.</p><h2>Additional browser checks</h2><p>Firefox desktop and Chrome Pixel 7 emulation: project identity, calculated distance, visible map bounds, separate search/card, and hidden initial layer drawer. Mobile emulation is not a real Android or iPhone result.</p><table><thead><tr><th>Browser</th><th>REPD</th><th>Outcome</th><th>Evidence</th></tr></thead><tbody>'+rows+'</tbody></table><p><a href="evidence/five-journeys.json">Measured results</a> · <a href="evidence/real-chrome-five.json">Real Chrome record</a></p><p>Remaining: other missing-location records including 11613; general Parquet search; actual device testing. Previous build claims about print/save are not re-certified by these arrival tests.</p>')
shutil.copytree(D,W/'testcode'/G,dirs_exist_ok=True)
# Snapshot latest remote homepage, preserving concurrent Claude publications.
p=W/'index.html';raw=p.read_bytes();s=raw.decode('utf8');F=W/'homepage_versions';n=max(int(p.stem.split('v')[-1]) for p in F.glob('homepage_v*.html'))+1
snap=F/f'homepage_v{n:03d}.html';before=len(list(F.iterdir()));snap.write_bytes(raw)
head=subprocess.check_output(['git','-C',str(W),'rev-parse','HEAD']).decode().strip()
with (F/'README.md').open('a',encoding='utf8') as o:o.write(f'\n\n## Snapshot v{n:03d}\nSource: {head}. File {snap.name}. Folder files before {before}, after {before+1}.\nLines {len(s.splitlines())}; words {len(s.split())}; characters {len(s)}. SHA256 {hashlib.sha256(raw).hexdigest()}.\nIntention: append Test Code {G}, preserving Claude builds and previous Test Code links.\n')
assert '<h2>Test Code</h2>' in s
s=s.replace('<h2>Test Code</h2>','<h2>Test Code</h2>\n<p><a href="./testcode/'+G+'/">Grid calculation and mobile layout correction - '+G+' UTC</a>: five Chrome MAP journeys with screenshots; Morgan uses an attributed approximate lease-area centre.</p>').replace('Latest correction - 202609051214 UTC','Earlier correction - 202609051214 UTC');write(p,s)
print(snap.name)
