import fs from 'node:fs';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { fileURLToPath } from 'node:url';
const ROOT=fileURLToPath(new URL('./', import.meta.url));
const families=Array.from({length:241},(_,i)=>i+1);
const records=Object.fromEntries(families.map(n=>[n,{n,names:['function'+n],lines:[n],repos:['Ventusltd/testcode'],places:[],uses:[],used_by:[]} ]));
records[1].used_by=families.slice(1,70).map(n=>({family:n,name:'function'+n}));
let failBucket=false;
const dom=new JSDOM(fs.readFileSync(ROOT+'index.html','utf8'),{url:'https://example.test/#',runScripts:'outside-only',pretendToBeVisual:true});
dom.window.fetch=async url=>{
 if(url.endsWith('blocks/blocks.json'))return {ok:true,json:async()=>({blocks:[{symbol:'Vn',number:1,title:'Nearest substation',category:'grid',depends_on:[],used_by:[]}],categories:[{id:'grid',title:'Grid',colour:'#00e5ff'}]})};
 if(url.endsWith('blocks/families.json'))return {ok:true,json:async()=>({Vn:families,unnamed:[1,241]})};
 if(url.endsWith('code/index.json'))return {ok:true,json:async()=>({families:241,lines:241,bucket_size:500})};
 if(url.endsWith('code/names.json'))return {ok:true,json:async()=>({function1:[1]})};
 if(url.includes('code/f/'))return failBucket?{ok:false,status:503}:{ok:true,json:async()=>records};
 throw Error('Unexpected fixture URL '+url);
};
const tick=()=>new Promise(r=>setTimeout(r,20));
dom.window.eval(fs.readFileSync(ROOT+'core.js','utf8')+'\n'+fs.readFileSync(ROOT+'journey.js','utf8')+'\nwindow.fixtureU=U;');await tick();
const w=dom.window,d=w.document;
const clickText=(selector,text)=>{const e=[...d.querySelectorAll(selector)].find(e=>e.textContent.includes(text));assert.ok(e,'Visible control: '+text);e.click();};
clickText('#blocks button','Vn');await tick();
const familySection=[...d.querySelectorAll('section.box')].find(e=>e.textContent.startsWith('Contains'));
assert.ok(familySection.textContent.includes('1–24 of 241'));
for(let i=0;i<10;i++)familySection.querySelector('[aria-label="Next page"]').click();
assert.ok(familySection.textContent.includes('241–241 of 241'));
clickText('#subject button','#241');await tick();assert.equal(w.location.hash,'#family=241');assert.match(d.querySelector('.subject-title').textContent,/#241/);
console.log('PASS: a family past the former 200-item cutoff is reachable by paging and click');
w.eval("navigate('family',1)");await tick();
assert.equal([...d.querySelectorAll('#subject button')].filter(b=>b.textContent.includes('Contained in')).length,2);
const used=[...d.querySelectorAll('section.box')].find(e=>e.textContent.startsWith('Used by'));
for(let i=0;i<4;i++)used.querySelector('[aria-label="Next page"]').click();
assert.match(used.textContent,/65–69 of 69/);clickText('#subject button','#70');await tick();assert.equal(w.location.hash,'#family=70');
console.log('PASS: every recorded membership and relationship past the former 40-link cutoff is reachable');
d.querySelector('#back').click();await tick();assert.equal(w.location.hash,'#family=1');assert.match(d.querySelector('.subject-title').textContent,/#1 /);
console.log('PASS: browser history restores the preceding family');
failBucket=true;w.eval("fixtureU.buckets.clear(); navigate('family',2)");await tick();assert.match(d.querySelector('[role=alert]').textContent,/503/);
failBucket=false;clickText('#subject button','Retry');await tick();assert.match(d.querySelector('.subject-title').textContent,/#2 /);
console.log('PASS: missing bucket fails visibly and Retry recovers after the data becomes available');
w.eval("navigate('family','not-a-number')");await tick();assert.match(d.querySelector('[role=alert]').textContent,/integer/);
console.log('PASS: invalid deep links fail visibly');
dom.window.close();
