import{SOURCE,MODULE_URL,parseNumber,parseUnits,calculate}from'./model.mjs';const $=id=>document.getElementById(id);const fmt=n=>n!==0 && Math.abs(n)<.000001?n.toExponential(4):n.toLocaleString('en-GB',{maximumFractionDigits:3});let engine,current;
$('code').href=`https://github.com/${SOURCE.repository}/blob/${SOURCE.commit}/${SOURCE.file}`;$('proof').href=`https://github.com/${SOURCE.repository}/blob/${SOURCE.commit}/proofs/firm-capacity.proof.mjs`;$('provenance').textContent=`${SOURCE.repository} / ${SOURCE.commit} / ${SOURCE.file}\nSHA256 ${SOURCE.sha256}`;
function draw(){const{inputs,assessment,largestUnitMva}=current;const scale=Math.max(assessment.installedMva,inputs.demandMva);const lost=inputs.units.indexOf(largestUnitMva);$('allUnits').replaceChildren();$('remaining').replaceChildren();const segment=(value,index,removed,parent)=>{const span=document.createElement('span');span.className=`segment${removed?' removed':''}`;span.style.width=`${value/scale*100}%`;span.title=`Stated unit${index+1}: ${fmt(value)}MVA${removed?' · excluded from remainder':''}`;if(value/scale>=.12)span.textContent=`${fmt(value)}`;parent.append(span);};inputs.units.forEach((value,i)=>segment(value,i,false,$('allUnits')));inputs.units.forEach((value,i)=>{if(i!==lost)segment(value,i,false,$('remaining'));});segment(inputs.units[lost],lost,true,$('remaining'));$('demandMarker').style.left=`${inputs.demandMva/scale*100}%`;$('scale').textContent=`Both bars share a0–${fmt(scale)}MVA scale. Segment widths show stated ratings.`;$('unitLabels').textContent=inputs.units.map((v,i)=>`Unit${i+1}: ${fmt(v)}MVA`).join(' · ');}
function refresh(){current=null;$('download').disabled=true;if(!engine)return;try{current=calculate(engine,{units:parseUnits($('units').value),demandMva:parseNumber($('demand').value)});const a=current.assessment;$('installed').textContent=`${fmt(a.installedMva)}MVA`;$('firm').textContent=`${fmt(a.firmMva)}MVA`;$('quick').textContent=`${fmt(a.installedMva)}MVA installed − ${fmt(current.largestUnitMva)}MVA largest = ${fmt(a.firmMva)}MVA arithmetic remainder`;$('demandLabel').textContent=`Demand marker: ${fmt(a.demandMva)}MVA`;$('comparison').textContent=a.withinFirm?'The stated demand is within the largest-unit-loss arithmetic remainder. This is not security or connection approval.':`${fmt(a.shortfallMva)}MVA above the largest-unit-loss arithmetic remainder. This does not say every possible unit outage has the same result.`;$('utilisation').textContent=typeof a.utilisationOfFirm==='number'?`Demand / arithmetic remainder: ${fmt(a.utilisationOfFirm*100)}%. Demand / installed: ${fmt(a.utilisationOfInstalled*100)}%.`:`No finite firm-utilisation percentage: the arithmetic remainder is zero. Demand / installed: ${fmt(a.utilisationOfInstalled*100)}%.`;$('record').textContent=JSON.stringify(current,null,2);$('result').hidden=false;$('error').hidden=true;$('status').textContent='Computed by the pinned module · synthetic stated values';$('download').disabled=false;draw();}catch(error){current=null;$('result').hidden=true;$('error').hidden=false;$('error').textContent=`REFUSED · ${error.name}: ${error.message}`;$('quick').textContent='Input refused; previous result cleared.';$('status').textContent='No current calculation.';$('record').textContent='No current result.';}}
$('controls').addEventListener('submit',event=>{event.preventDefault();refresh();});$('controls').addEventListener('input',refresh);document.querySelectorAll('[data-preset]').forEach(button=>button.addEventListener('click',()=>{$('units').value=button.dataset.preset;$('demand').value=button.dataset.preset==='30'?'10':'42';refresh();}));
for(const[id,reason]of Object.entries({wafer:'No numbered line established for this element: no issued code-line mapping has been verified for these synthetic transformer inputs.',application:'No registered application URL established for this calculation.',tools:'No manifest layer established for this calculation; no tool target is invented.'}))$(id).addEventListener('click',()=>{$('handoff').textContent=reason;});
$('download').addEventListener('click',()=>{if(!current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(current,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='firm-arithmetic.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
try{engine=await import(MODULE_URL);refresh();}catch(error){$('quick').textContent='Calculation module unavailable.';$('status').textContent='No substitute arithmetic.';$('error').hidden=false;$('error').textContent=error.message;}
if(document.modelContext?.registerTool){
  const lifecycle=new AbortController();addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'read_firm_arithmetic',description:'Read the current synthetic largest-unit-loss calculation without changing it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input || typeof input!=='object' || Array.isArray(input) || Object.keys(input).length)throw new TypeError('Expected empty object');return current?JSON.parse(JSON.stringify(current)):{available:false,status:$('status').textContent};}});
  register({name:'configure_firm_arithmetic',description:'Set synthetic MVA ratings and demand, then run the same visible arithmetic. Does not certify a connection or security.',inputSchema:{type:'object',properties:{units:{type:'array',minItems:1,maxItems:6,items:{type:'number',minimum:.001,maximum:1000}},demandMva:{type:'number',exclusiveMinimum:0,maximum:5000}},required:['units','demandMva'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!engine)throw new Error('Module unavailable');if(!input || typeof input!=='object' || Array.isArray(input) || Object.keys(input).some(key=>!['units','demandMva'].includes(key)))throw new TypeError('Unexpected fields');calculate(engine,input);$('units').value=input.units.join(', ');$('demand').value=String(input.demandMva);refresh();return JSON.parse(JSON.stringify(current));}});
}
