import{spawn}from'node:child_process';import{mkdir,writeFile,readFile}from'node:fs/promises';import path from'node:path';import{createHash}from'node:crypto';import assert from'node:assert/strict';import{SOURCE,MODULE_URL}from'./model.mjs';
const playwright=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');const output=process.env.PROOF_OUTPUT || path.resolve('browser-evidence');await mkdir(output,{recursive:true});const url=process.env.PAGE_URL || 'http://127.0.0.1:8779/';const server=process.env.PAGE_URL?null:spawn(process.platform==='win32'?'python':'python3',['-m','http.server','8779','--bind','127.0.0.1'],{stdio:'ignore'});const results=[];
try{
  for(let n=0;n<30;n++){try{if((await fetch(url)).ok)break;}catch{}if(n===29)throw Error('Preview unavailable');await new Promise(r=>setTimeout(r,100));}
  for(const name of(process.env.BROWSER_ENGINES || 'chromium,webkit').split(',')){
    const browser=await playwright[name].launch({headless:true,...(name==='chromium' && process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
    try{for(const width of[390,1400]){
      const context=await browser.newContext({viewport:{width,height:width===390?844:900},deviceScaleFactor:width===390?3:1,isMobile:width===390,hasTouch:width===390,acceptDownloads:true});const page=await context.newPage();page.setDefaultTimeout(12000);const errors=[],failed=[],responses=[];let negative=false;const receipt={engine:name,version:browser.version(),width,dpr:width===390?3:1,started:new Date().toISOString(),pass:false,errors,failed_requests:failed};
      page.on('pageerror',e=>{if(!negative)errors.push(e.message);});page.on('console',m=>{if(!negative && m.type()==='error')errors.push(m.text());});page.on('requestfailed',r=>{if(!negative)failed.push(r.url());});page.on('response',r=>{if(negative)return;if(r.status()>=400)failed.push(r.url());if(r.url()===MODULE_URL)responses.push(r.body().then(bytes=>({status:r.status(),sha256:createHash('sha256').update(bytes).digest('hex')})));});
      try{
        await page.goto(url);await page.waitForFunction(()=>document.querySelector('#firm').textContent==='30MVA');assert.equal(await page.locator('#installed').innerText(),'60MVA');assert.match(await page.locator('#utilisation').innerText(),/140%/);await page.waitForFunction(()=>Number(getComputedStyle(document.querySelector('.removed')).opacity)<=.251);await page.screenshot({path:path.join(output,`${name}-${width}-firm.png`),fullPage:true});
        await page.getByRole('button',{name:'Unequal units',exact:true}).click();assert.equal(await page.locator('#installed').innerText(),'120MVA');assert.equal(await page.locator('#firm').innerText(),'30MVA');assert.match(await page.locator('#comparison').innerText(),/does not say every possible unit outage/);
        await page.getByRole('button',{name:'One unit',exact:true}).click();assert.equal(await page.locator('#firm').innerText(),'0MVA');assert.match(await page.locator('#utilisation').innerText(),/No finite firm-utilisation/);
        await page.getByText('Machine detail',{exact:true}).click();const promise=page.waitForEvent('download');await page.locator('#download').click();const download=await promise;const filename=path.join(output,`${name}-${width}-single.json`);await download.saveAs(filename);const record=JSON.parse(await readFile(filename,'utf8'));assert.equal(record.assessment.utilisationOfFirm.value,'Infinity');assert.equal(record.assessment.firmMva,0);
        await page.locator('#units').fill('30,,30');assert.match(await page.locator('#error').innerText(),/finite number/);assert.equal(await page.locator('#result').isVisible(),false);assert.equal(await page.locator('#download').isDisabled(),true);await page.locator('#units').fill('30,30');await page.locator('#demand').fill('0');assert.match(await page.locator('#error').innerText(),/greater than zero/);
        await page.locator('#demand').fill('24');assert.match(await page.locator('#comparison').innerText(),/within the largest-unit-loss/);await page.getByRole('button',{name:'RUN · largest-unit loss',exact:true}).click();
        await page.locator('#wafer').click();assert.match(await page.locator('#handoff').innerText(),/No numbered line established/);assert.equal(await page.locator('#code').getAttribute('href'),`https://github.com/${SOURCE.repository}/blob/${SOURCE.commit}/${SOURCE.file}`);
        await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.removed').evaluate(e=>getComputedStyle(e).animationName),'none');receipt.overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(receipt.overflow,false);await page.screenshot({path:path.join(output,`${name}-${width}-details.png`),fullPage:true});
        receipt.source_responses=await Promise.all(responses);assert.ok(receipt.source_responses.length);for(const r of receipt.source_responses){assert.equal(r.status,200);assert.equal(r.sha256,SOURCE.sha256);}assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
        negative=true;await page.route(MODULE_URL,r=>r.abort('failed'));await page.reload();await page.waitForFunction(()=>document.querySelector('#quick').textContent.includes('module unavailable'));assert.equal(await page.locator('#result').isVisible(),false);assert.equal(await page.locator('#download').isDisabled(),true);receipt.module_unavailable_refused=true;receipt.native_webmcp='Not exercised in a supported native context.';receipt.pass=true;
      }catch(error){receipt.pass=false;receipt.error=error.stack;}finally{receipt.finished=new Date().toISOString();results.push(receipt);await context.close();}
    }}finally{await browser.close();}
  }
}finally{server?.kill();await writeFile(path.join(output,'receipt.json'),JSON.stringify({source_commit:process.env.GITHUB_SHA || null,url,results},null,2)+'\n');}
console.log(JSON.stringify({cases:results.length,passed:results.filter(r=>r.pass).length}));if(!results.length || results.some(r=>!r.pass))process.exitCode=1;
