// Grid Machine: active-click acceptance, with record then network-blocked replay.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/home/vikram/.local/share/globalgrid-worker/browser/node_modules/playwright');
const root=path.resolve(__dirname,'..'),stamp=process.argv[2],mode=process.argv[3];
if(!/^\d{8}T\d{6}Z$/.test(stamp)||!['record','offline'].includes(mode))throw Error('timestamp and record/offline required');
const out=path.resolve(process.env.GRIDMACHINE_EVIDENCE||('/home/vikram/.local/share/globalgrid-worker/pair-evidence/'+stamp));fs.mkdirSync(out,{recursive:true});
const cache=path.join(out,'mirror');fs.mkdirSync(cache,{recursive:true});
const report={pair_id:'GGPAIR-GM02-'+stamp,mode,started:new Date().toISOString(),cases:[],misses:[],errors:[],network_fetches:0,product_verdict:'NOT_EVALUATED',coverage:'Five actual PipelineNews MAP clicks; not the full estate or a reverse-direction acceptance test.'};
const types={'.js':'text/javascript','.mjs':'text/javascript','.html':'text/html','.css':'text/css','.json':'application/json','.geojson':'application/json','.wasm':'application/wasm','.parquet':'application/vnd.apache.parquet'};
const server=http.createServer((req,res)=>{try{let f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!f.startsWith(root+path.sep))return res.writeHead(403).end();if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');const bytes=fs.readFileSync(f);res.writeHead(200,{'content-type':types[path.extname(f)]||'application/octet-stream'}).end(bytes);}catch{res.writeHead(404).end();}});
let browser;
const checks=[{ref:'11386',tech:'all',status:'RESOLVED',mapped:true,source:'OFFICIAL_ACTIVE_REGISTER',control:true},{ref:'13429',tech:'all',status:'RESOLVED',mapped:true,source:'CROWN_ESTATE_LEASE_POINT_ON_SURFACE'},{ref:'13432',tech:'all',status:'RESOLVED_UNMAPPED',mapped:false,source:'NONE'},{ref:'IC-INTNED',tech:'interconnector',status:'RESOLVED'},{ref:'IC-INTVKL',tech:'interconnector',status:'NOT_DRAWABLE'}];
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,base=origin+`/sandbox/gm02/${stamp}/`;browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'chrome',chromiumSandbox:true});report.browser=browser.version();
for(const c of checks){const ctx=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
await ctx.route('**/*',async route=>{const req=route.request(),url=req.url();if(url.startsWith(origin+'/'))return route.continue();if(!/^https?:/.test(url))return route.continue();const key=crypto.createHash('sha256').update(JSON.stringify([req.method(),url,req.headers().range||''])).digest('hex'),meta=path.join(cache,key+'.json'),body=path.join(cache,key+'.bin');try{
if(fs.existsSync(meta)&&fs.existsSync(body)){const m=JSON.parse(fs.readFileSync(meta));return route.fulfill({status:m.status,headers:m.headers,body:fs.readFileSync(body)});}
if(mode==='offline'){report.misses.push({url,range:req.headers().range||null});return route.abort('internetdisconnected');}
report.network_fetches++;const response=await route.fetch({timeout:45000}),bytes=await response.body(),headers=response.headers();delete headers['content-encoding'];delete headers['transfer-encoding'];headers['content-length']=String(bytes.length);fs.writeFileSync(body,bytes);fs.writeFileSync(meta,JSON.stringify({url,method:req.method(),range:req.headers().range||null,status:response.status(),headers,sha256:crypto.createHash('sha256').update(bytes).digest('hex')}));return route.fulfill({status:response.status(),headers,body:bytes});
}catch(e){report.errors.push({url,error:String(e).slice(0,200)});try{await route.abort();}catch{}}});
const p=await ctx.newPage();let result={ref:c.ref,control:!!c.control,pass:false};try{await p.goto(base+'pipeline/',{waitUntil:'domcontentloaded'});await p.locator('#tbody .atlaslink').first().waitFor({timeout:45000});await p.locator(`[data-technology="${c.tech}"]`).click();await p.locator('#search').fill(c.ref.replace('IC-',''));const link=p.locator(`#repd-${c.ref} .atlaslink`);await link.waitFor({timeout:15000});const [a]=await Promise.all([ctx.waitForEvent('page'),link.click()]);await a.waitForLoadState('domcontentloaded');await a.waitForFunction(({ic})=>ic?['RESOLVED','NOT_DRAWABLE','FAILED'].includes(window.__GRIDATLAS_INTERCONNECTORS__?.arrival?.status):['RESOLVED','RESOLVED_UNMAPPED','FAILED'].includes(window.__GRIDATLAS_PLACE_SEARCH__?.deep_link?.status),{ic:c.tech==='interconnector'},{timeout:60000});await a.waitForTimeout(6000);
Object.assign(result,await a.evaluate(()=>({url:location.href,pair:window.__GGPAIR__,identity:window.__GRIDATLAS_PLACE_SEARCH__?.deep_link,interconnector:window.__GRIDATLAS_INTERCONNECTORS__?.arrival?((a)=>({status:a.status,framed:a.framed,ends:(a.ends||[]).map(e=>e?({nearest_km:e.nearest_km,nearest_name:e.nearest_name,coverage:e.coverage}):null),search_km:a.search_km}))(window.__GRIDATLAS_INTERCONNECTORS__.arrival):null,engine:window.__GRIDATLAS_NEON_LINKS__?{installed:window.__GRIDATLAS_NEON_LINKS__.installed,links_drawn:window.__GRIDATLAS_NEON_LINKS__.links_drawn,reconciliation:window.__GRIDATLAS_NEON_LINKS__.arrival_reconciliation}:null,bounds:window.__GRIDATLAS_V9_MAP__?.getBounds()?.toArray(),failure_card:/identity check failed|did not fly to a safe map point/i.test(document.body.innerText)})));
const pairOK=result.url.startsWith(base+'atlas/')&&result.pair?.pair_id===report.pair_id&&!result.failure_card;
result.pass=c.tech==='interconnector'?Boolean(pairOK&&result.interconnector?.status===c.status&&result.pair.engine_calls>0&&result.interconnector?.ends?.[0]?.nearest_km!=null):Boolean(pairOK&&result.identity?.status===c.status&&result.identity?.mapped===c.mapped&&result.identity?.coordinate_source===c.source&&(!c.control||result.engine?.links_drawn>0));
await a.screenshot({path:path.join(out,mode+'-'+c.ref+'.png')});await a.close();
}catch(e){result.error=String(e);}
report.cases.push(result);await ctx.close();fs.writeFileSync(path.join(out,mode+'.json'),JSON.stringify(report,null,2));if(c.control&&!result.pass){report.product_verdict='HARNESS_INVALID';break;}}
if(report.product_verdict!=='HARNESS_INVALID')report.product_verdict=report.cases.length===checks.length&&report.cases.every(c=>c.pass)&&!report.misses.length?'PASS':report.cases.some(c=>c.error)?'BLOCKED_HARNESS':'FAIL';
})().catch(e=>{report.errors.push(String(e.stack));report.product_verdict='BLOCKED_HARNESS';}).finally(async()=>{if(browser)await browser.close();server.close();report.finished=new Date().toISOString();fs.writeFileSync(path.join(out,mode+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({mode,verdict:report.product_verdict,cases:report.cases.map(c=>({ref:c.ref,pass:c.pass,error:c.error})),misses:report.misses.length,evidence:out}));process.exitCode=report.product_verdict==='PASS'?0:1;});
